TypeScriptの導入
kenta-0615/react-task-app pull request #10
Opened 2022-05-01 23:14 UTC by kenta-0615

# 着手事項
- TypeScriptの導入
- npm i typescriptでインストール
# エラー発生内容
- TypeScriptを導入したブランチがマージされていたので新たにブランチが切れなくなった
  - 解決方法：変更したファイルをstashかcommitするようにエラーに出ていたため、今回は新たにブランチをりたいため、stashをして一旦退避させた
  - 対策：今後インストールなどする際は、ブランチがマージされていないかどうかを確認してインストールをする
- CONFLICT ERRORの発生
   - 発生原因：今回の開発環境内にpackage-lock.jsonとyarn-lockが対立（衝突）してどっちを使うの
   CONFLICTが起きた。
   - 解決方法：開発環境において、package-lock（npm）かyarn-lockをどちらを使うか一つに絞るため、
   yarn-lockを削除package-lockだけを使うようにした。

2022-05-01 23:22 UTC, taishi1116 commented
@kenta-0615 
通話でも話した部分だけど質問です。

これって本当にtypescript動いている証明ってどこで取れますか?

2022-05-01 23:28 UTC, taishi1116 commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
@kenta-0615 

今回yarn.lockを削除したので、今後はnpmで運用する認識です。
これはreadmeに追記するべきだと思います

2022-05-07 13:42 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
# TypeScriptのエラー対処
## 着手事項
- 全てのファイルの拡張子を.tsxへ変更
- 全てのファイルのtypeの型の定義付け
- tsconfig.jsonを追加し、モジュールエラーを解消
- README.mdのインストール方法をnpmのみに記載変更
## 確認事項
- Webの方に今回作ったタスクが表示されることを確認
- ターミナルにもエラーが発生していないことを確認
- Webの検証でもエラーが発生していないことを確認
# 結論
* TypeScriptの導入成功

2022-05-07 14:56 UTC, taishi1116 requested changes
@kenta-0615 

何点かコメントしました！

2022-05-07 14:56 UTC, taishi1116 commented on package.json
> +    "tsconfig.json": "^1.0.11",
`tsconfig.json`というパッケージって存在する?
篠田の認識だとtsconfig.jsonはtypescriptの設定ファイルなのでパッケージとして取り込むことはない認識です

2022-05-07 14:56 UTC, taishi1116 commented on src/components/PasswordInput.tsx
> +	errorMessage: string;
`{p.errorMessage && <p>{p.errorMessage}</p>}`という実装なのでerrorMessageはundefinedの可能性があるのではないでしょうか?

2022-05-07 14:56 UTC, taishi1116 commented on src/components/TextName.tsx
> +						onClick={() => {}}
onclick使わないなら削除しときましょうか

2022-05-09 05:58 UTC, kenta-0615 commented on src/components/PasswordInput.tsx
> +	errorMessage: string;
@taishi1116 
errorMessage: string; =>errorMessage?: stringにしないといけないという意味ですか？

2022-05-09 07:14 UTC, taishi1116 commented on src/components/PasswordInput.tsx
> +	errorMessage: string;
その認識です！
`{p.errorMessage && <p>{p.errorMessage}</p>}`という記述がありますが、これは`p.errorMessage`が存在する場合pタグで文字をレンダリングするという意味だと思います！
ただ、propsの型を見てみるとerrorMessageは必ず存在するようになっているので実装とpropsの引数の整合性が異なるように感じました！

```ts

export const PasswordInput: React.FC<Props> = (p) => {
	return (
		<div>
			<form>
				<label>PASS:</label>
				<input
					type="password"
					name="password"
					value={p.password}
					onChange={p.onChangePass}
				/>
			</form>
			<form>
				<label>REPASS:</label>
				<input
					type="password"
					name="confirm"
					value={p.confirmPassword}
					onChange={p.onChangeConfirm}
				/>
                       
				{p.errorMessage && <p>{p.errorMessage}</p>}
			</form>
		</div>
	);
};
```

2022-05-09 17:26 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
# 指摘部分の修正
- PasswordInput.tsxのerrorMessageの修正
- TextName.tsxのonClickを削除

2022-05-09 17:26 UTC, kenta-0615 commented on src/components/PasswordInput.tsx
> +	errorMessage: string;
@taishi1116 
了解です！
直ちに修正します！

2022-05-10 01:20 UTC, taishi1116 commented on src/components/TelephoneNumberInput.tsx
> +	changeTel: (event: any) => void;
ごめん、ここの変数名の指摘抜けていた
`TelephoneNumberInput`というコンポーネントから電話番号入力という意味合いはわかるので`telephoneNumberErrorMessage`といったprops名は冗長だと感じた！
下記のような形でどうですかね?

- onChange
- value
- errorMessage

2022-05-10 01:21 UTC, taishi1116 requested changes
@kenta-0615 
追加で一点だけコメントした！

2022-05-10 12:39 UTC, so0601pk approved these changes
@kenta-0615
個人的に感じたことなので、そう思う人もいるんだくらいで読んでもらえればと思います！
---
# Readmeの書き方について
### パッケージ管理ツールについて（npm,yarn）
パッケージ管理ツールは初めからReadmeで決めておくのが良いと思います！
今回はTypeScript導入のためにyarnを辞めてnpmで統一したけど、
もし以前のまま、どちらのパッケージ管理でも
packageのインストールをしてもよい形式だと
何も知らない人からすると、まずその違いを調べるところから
始めるような気がするかな。
（自分もどっちでインストールするか一瞬悩んだ）

### 環境の立ち上げ方について
もっと親切にするなら環境立ち上げまでのコマンドを全てReadmeに書いておくと
より誰にでも環境を立ち上げられるようになると思います！

【例】

- このリポジトリをクローン
    - `git clone 【該当のリポジトリのURL】`
- packageのinstall
    - `cd 【cloneしたディレクトリ】`
    - `yarn install`
- ローカル環境の立ち上げ
    - `yarn start`

2022-05-11 22:59 UTC, kenta-0615 reviewed
@taishi1116 @so0601pk 
# package.jsonのtypescriptの追加
- tsconfig.jsonをpackag.jsonjから削除
- npm installを実施
- typescriptを再度導入できたと思うので確認お願い致します。

2022-05-12 08:56 UTC, taishi1116 approved these changes
![LGTM](https://image.lgtmoon.dev/72026)

2022-05-12 12:27 UTC, taishi1116 commented
![LGTM](https://image.lgtmoon.dev/165899)

2022-05-12 12:29 UTC, merged