課題２のReact-router-dom実装
kenta-0615/react-task-app pull request #4
Opened 2022-04-25 06:23 UTC by kenta-0615

# 着手したこと
- react-router-domをインストール
- Task2Page作成
- LoginPageとTask2Pageのページを作成

2022-04-25 06:26 UTC, taishi1116 commented on src/App.jsx
> +    <ul>
ここは今後増える可能性があるのでMenuコンポーネントで作ってまとめる。
それをimportしたらAppコンポーネントがスッキリすると思います！

2022-04-25 08:36 UTC, taishi1116 commented on src/App.jsx
> +    <ul>
@kenta-0615 
これ何か詰まっている?下記のコンポーネント作るだけだと思っているので、認識違うなら合わせたい


```ts

const Menu =()=>{
return (
 <ul>
      <li>
        <a href="/">LoginPage</a>
      </li>
      <li>
        <a href="/Task2Page">Task2Page</a>
      </li>
    </ul>
)}
```

2022-04-26 11:15 UTC, kenta-0615 commented on src/App.jsx
> +    <ul>
@taishi1116 
認識が違った感じです。
修正とブランチのクローズします。

2022-04-27 07:27 UTC, kenta-0615 commented on src/App.jsx
> +    <ul>
@taishi1116 
# 現在の認識
- ページをまとめるためにMenuコンポーネントを作る
- コンポーネントの場所は、pagesに作る
---
# 前の認識
- 前は、ページをまとめるドロップダウンメニューを作る
- その中にページをまとめて分かりやすくする

2022-04-27 07:58 UTC, kenta-0615 reviewed
@taishi1116 
## 着手事項
- Menuコンポーネントの実装

2022-04-28 00:55 UTC, taishi1116 commented
@kenta-0615 
エラーでているので全部の解決おねがい！

![スクリーンショット 2022-04-28 9 55 36](https://user-images.githubusercontent.com/58138538/165655060-22490752-e182-4591-b319-73d8a7f8343c.png)

2022-04-28 00:56 UTC, taishi1116 commented on src/App.jsx
> +    <ul>
ドロップダウンまでやる要件はなかったね

2022-04-28 00:58 UTC, taishi1116 requested changes

2022-04-28 00:58 UTC, taishi1116 commented on src/App.jsx
>  import { memo } from "react";
App.tsxメモしているけど、大丈夫?
コンポーネントの再レンダリングを抑えるためにメモする認識なんだけど、Appをメモするってことはアプリ全体の再レンダリングを抑えることになるから、バグを産みそう！

メモ化によるパフォーマンス対応は今はやらなくていいです
まずはパフォーマンス考えずに、基本実装が書けるようになりましょう

2022-04-28 10:02 UTC, taishi1116 commented on src/App.jsx
> +    <ul>
[16163a5](https://github.com/kenta-0615/react-task-app/pull/4/commits/16163a5ecba33c9e302295a8e9aca667bebd7395) こちらで修正

2022-04-29 06:34 UTC, taishi1116 commented on src/App.jsx
>  import { memo } from "react";
[2295a5f](https://github.com/kenta-0615/react-task-app/pull/4/commits/2295a5fd8aaf573e3b56b73eb6b802b3dbd88bf3) こちらで直しました

2022-04-29 06:42 UTC, taishi1116 requested changes
@kenta-0615 
追加コメントしたので確認お願い！

2022-04-29 06:42 UTC, taishi1116 commented on src/pages/Menu.jsx
> +export const Menu = () => {
src/pagesにMenuコンポーネントが置かれているけど、これは正しいですか?
メニューは各ページで利用されるパーツの認識であり、ページそのものではないと思います！

よってコンポーネントの置き場所を再検討してほしいです

2022-04-29 06:43 UTC, taishi1116 approved these changes

2022-04-29 06:53 UTC, taishi1116 commented
# 残タスク

- [ ] Menuコンポーネントをcomponentsディレクトリに移行
- [ ] componentsディレクトリは平くする

2022-04-29 07:09 UTC, merged